# Generated by Django 5.0.4 on 2024-04-07 17:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MultipleServiceImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image/')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('ER', 'Erkak'), ('AY', 'Ayol')], max_length=2)),
                ('status', models.CharField(choices=[('ST', 'Standard'), ('LY', 'Lyuks')], default='ST', max_length=2)),
                ('arrival_date', models.DateField()),
                ('time_to_leave', models.DateField()),
                ('tel_number', models.CharField(max_length=20)),
                ('who', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('open', models.DateTimeField()),
                ('clode', models.DateTimeField()),
                ('location', models.CharField(max_length=50)),
                ('who_has_this', models.CharField(choices=[('ST', 'Standard'), ('LY', 'Lyuks')], default='ST', max_length=2)),
                ('tel_number', models.CharField(max_length=20)),
                ('info', models.TextField(max_length=200)),
                ('image', models.ImageField(upload_to='image/')),
                ('qr_code', models.ImageField(blank=True, upload_to='qr_code/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.category')),
                ('more_images', models.ManyToManyField(blank=True, to='api.multipleserviceimages')),
            ],
        ),
        migrations.AddField(
            model_name='multipleserviceimages',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.services'),
        ),
        migrations.CreateModel(
            name='UsedServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.DateTimeField(auto_now_add=True)),
                ('which_services', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.services')),
                ('who_used', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.profile')),
            ],
        ),
    ]
