# Generated by Django 5.0.4 on 2024-04-07 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='services',
            old_name='clode',
            new_name='close',
        ),
    ]
